# Generated by Django 5.0.2 on 2024-04-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('game_description', models.TextField()),
                ('game_genre', models.CharField(max_length=50)),
                ('game_rating', models.CharField(max_length=50)),
                ('game_completed', models.BooleanField()),
                ('time_to_beat', models.TextField()),
            ],
        ),
    ]
