# Generated by Django 5.0.2 on 2024-04-17 20:04

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_completed',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_rating',
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_library.developer'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='genre_name_case_insensitive_unique', violation_error_message='Genre already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='game_library.genre'),
        ),
    ]
