# Generated by Django 5.0.2 on 2024-04-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_library', '0003_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
