# Generated by Django 5.0.2 on 2024-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_library', '0005_platform_game_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(choices=[('Singleplayer', 'Singleplayer'), ('Multiplayer', 'Multiplayer'), ('Both', 'Both')], default='Singleplayer', max_length=20),
        ),
    ]
