# Generated by Django 5.0.2 on 2024-05-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_library', '0006_alter_game_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
